name: .NET Build and Deploy to IIS via SSH

on:
  push:
    branches:
      - master  # or your production branch

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Check out the repo content
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Updated to .NET 8.0

    - name: Build and publish
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish --no-restore

    - name: Copy files to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "publish/*"
        target: "/var/www/yourapplication"  # Adjust the target path to your server's path

    - name: Restart IIS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          iisreset /restart
          # Additional commands to manage application pools or other settings can be added here
