name: .NET Core Build and Deploy

on:
  push:
    branches:
      - master      # Trigger the workflow on pushes to the master branch
  

jobs:
  build:
    runs-on: windows-latest   # Use Windows runner if your development is on Windows

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    #- name: Restore dependencies
    #  run: dotnet restore SynelInitialTest.sln
    #  working-directory: .
    - name: List files in root directory
      run: Get-ChildItem -Path ./
      shell: pwsh

    - name: List files in src directory
      run: Get-ChildItem -Path ./SynelInitialTest/src/
      shell: pwsh
    - name: List files in src/Employees.Web directory
      run: Get-ChildItem -Path ./src/Employees.Web/
      shell: pwsh
    - name: Restore dependencies for specific project
      run: dotnet restore ./SynelInitialTest/src/Employees.Web/Employees.Web.csproj
    
    - name: Build and publish specific project
      run: |
        dotnet build ./src/Employees.Web/Employees.Web.csproj --no-restore -c Release
        dotnet publish ./src/Employees.Web/Employees.Web.csproj -c Release -o out
      working-directory: .

    - name: Publish
      shell: cmd
      run: dotnet publish -c Release -o ./myapp #./src/Employees.Web/Employees.Web.csproj -c Release -o out
      #working-directory: .

   # - name: List output for debugging
   #   run: dir out /B /A-D  # 'dir' command for Windows
   #   working-directory: ./src/Employees.Web

    - name: Deploy to Server (IIS)
      shell: cmd
      run: |
        iisreset /stop
        xcopy /s /y .\myapp\* C:
        iisreset /start
      #uses: appleboy/scp-action@master
      #with:
      #  host: ${{ secrets.SERVER_IP }}
      #  username: ${{ secrets.SERVER_USERNAME }}
      #  password: ${{ secrets.SERVER_PASSWORD }}
      #  port: ${{ secrets.SERVER_PORT }}
      #  source: "./src/Employees.Web/out/*"
      #  target: "/remote/directory/path"
